version: '3'

services:
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    #volumes:
      #- </path/to/smokeping/config>:/config
      #- </path/to/smokeping/data>:/data
    ports:
      - 80:80
    restart: unless-stopped