version: '3'

services:
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /ba-volumes/smokeping/config:/config
      - /ba-volumes/smokeping/data:/data
    ports:
      - 80:80
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: raspi.fritz.box # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /ba-volumes/netdata/netdataconfig:/etc/netdata
      - /ba-volumes/netdata/netdatalib:/var/lib/netdata
      - /ba-volumes/netdata/netdatacache:/var/cache/netdata
      - /ba-volumes/netdata/etc/passwd:/host/etc/passwd:ro
      - /ba-volumes/netdata/etc/group:/host/etc/group:ro
      - /ba-volumes/netdata/proc:/host/proc:ro
      - /ba-volumes/netdata/sys:/host/sys:ro
      - /ba-volumes/netdata/etc/os-release:/host/etc/os-release:ro
