version: "3.3"

services:

  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - '443:443'
      - "8080:8080"
    #volumes:
      #- "ba-volumes/docker.sock:/var/run/docker.sock:ro"

  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    #volumes:
      #- ba-volumes/smokeping/config:/config
      #- ba-volumes/smokeping/data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`smokeping.ba.tulpow.de`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  
  elastic:
    image: docker.elastic.co/beats/elastic-agent:8.2.2
    container_name: elastic-agent
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - FLEET_ENROLLMENT_TOKEN={enrollment-token}
      - FLEET_ENROLL=1
      - FLEET_URL={fleet-server-url}
